trigger: none

pool:
  vmImage: windows-latest

variables:

 - group: windows-vm-var

stages:
  - stage: Install_and_build_packer_stage
    jobs:
      - job: installandbuildimage
        steps:
          - task: PowerShell@2
            displayName: download and install packer
            inputs:
              targetType: 'inline'
              script: |
                $url = "https://releases.hashicorp.com/packer/1.8.2/packer_1.8.2_windows_amd64.zip"
                $outpath = "$(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64.zip"
                Invoke-WebRequest -Uri $url -OutFile $outpath -Verbose
                Expand-Archive "$(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64.zip" -DestinationPath "$(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64" -Verbose
                $(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64/packer.exe --version 
                $(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64/packer.exe init $(System.DefaultWorkingDirectory)

          - task: PowerShell@2
            displayName: 'Packer validate'
            inputs:
              targetType: 'inline'
              script: |
                $(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64/packer.exe validate $(System.DefaultWorkingDirectory)/windows.pkr.hcl

          - task: PowerShell@2
            displayName: 'Packer build'
            inputs:
              targetType: 'inline'
              script: |

                $(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64/packer.exe build --var-file=$(System.DefaultWorkingDirectory)/windowsvariable.pkr.hcl $(System.DefaultWorkingDirectory)/windows.pkr.hcl