trigger: none

pool:
  vmImage: windows-latest

variables:

 - group: windows-vm-var

stages:
  - stage: Install_and_build_packer_stage
    jobs:
      - job: installandbuildimage
        steps:
          - task: PowerShell@2
            displayName: download and install packer
            inputs:
              targetType: 'inline'
              script: |
                $url = "https://releases.hashicorp.com/packer/1.8.2/packer_1.8.2_windows_amd64.zip"
                $outpath = "$(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64.zip"
                Invoke-WebRequest -Uri $url -OutFile $outpath -Verbose
                Expand-Archive "$(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64.zip" -DestinationPath "$(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64" -Verbose
                $(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64/packer.exe --version 

          - task: PowerShell@2
            displayName: 'Packer init'
            inputs:
              targetType: 'inline'
              script: |
                $(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64/packer.exe init $(System.DefaultWorkingDirectory)/windows.pkr.hcl
          - task: PowerShell@2
            displayName: 'Packer validate'
            inputs:
              targetType: 'inline'
              script: |
                $(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64/packer.exe validate $(System.DefaultWorkingDirectory)/windows.pkr.hcl

          - task: PowerShell@2
            displayName: 'Packer build'
            inputs:
              targetType: 'inline'
              script: |
                  $(System.DefaultWorkingDirectory)/packer_1.8.2_windows_amd64/packer.exe build \
                  -var "client_id=$(client_id)" \
                  -var "client_secret=$(client_secret)" \
                  -var "build_resource_group_name=$(build_resource_group_name)" \ 
                  -var "subscription_id=$(subscription_id)" \
                  -var "tenant_id=$(tenant_id)" $(System.DefaultWorkingDirectory)/windows.pkr.hcl
